{% set name = "pdata" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/govenius/pdata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d3fd45241f38ebdf59d9acc19e323c98bca485267067812b0369db2b1c3cf346

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - jsondiff
    - ipywidgets
    - ipympl
    - ipylab
    - matplotlib-base
    - pytz
    - python-dateutil
    - requests
    - ipykernel
    - ipython
    - notebook
    - uncertainties
    - xarray


test:
  imports:
    - numpy
    - pdata
    - pdata.procedural_data
    - pdata.analysis.dataview
    - pdata.analysis.dataexplorer
  source_files:
    - test/run_test.py
  requires:
    - pip
  commands:
    - pip check
    - python test/run_test.py

about:
  home: https://pdata.readthedocs.io/
  summary: Simple-to-understand and robust data storage for experimental data
  description: |
    This procedural data storage package provides a self-contained interface focused
    exclusively on storing and reading experimental data, using an approach independent
    of the specific measurement framework used for instrument control.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pdata.readthedocs.io/
  dev_url: https://github.com/govenius/pdata

extra:
  recipe-maintainers:
    - govenius
