{% set name = "pdata" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/govenius/pdata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 97fd82b0874728fefa56b0ee3dacbba39af3a030247754fbe5ee8808c538fb0b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<39 or (unix and (not py>39)) or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - numpy
    - cython
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - jsondiff
    - ipywidgets
    - ipympl
    - ipylab
    - matplotlib-base
    - pytz
    - python-dateutil
    - requests
    - ipykernel
    - ipython
    - notebook
    - uncertainties
    - xarray
    - jinja2


test:
  imports:
    - numpy
    - pdata
    - pdata.procedural_data
    - pdata.analysis.dataview
    - pdata.analysis.dataexplorer
    - pdata.analysis.fast_parser.tabular_data_parser
  source_files:
    - test/run_test.py
  requires:
    - pip
  commands:
    - pip check
    - python -X utf8 test/run_test.py

about:
  home: https://pdata.readthedocs.io/
  summary: Simple-to-understand and robust data storage for experimental data
  description: |
    This procedural data storage package provides a self-contained interface focused
    exclusively on storing and reading experimental data, using an approach independent
    of the specific measurement framework used for instrument control.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - pdata/static/XARRAY_LICENSE
    - pdata/static/ICOMOON_LICENSE
  doc_url: https://pdata.readthedocs.io/
  dev_url: https://github.com/govenius/pdata

extra:
  recipe-maintainers:
    - govenius
